pipeline {
    agent any
  //triggers {pollSCM('* * * * *')}
  stages {
    stage('Checkout') {
      steps {
        // Get some code from a GitHub repository
        git branch: "newVersion", url: 'https://github.com/hrhowell/ec2P2.git'
	
      }
    }
        stage('Build') {
      steps {
        sh 'chmod a+x Backend/mvnw'
        sh './Backend/mvnw clean package -DskipTests=true'
      }

          post {
        always {
          archiveArtifacts 'target/*.jar'
        }
          }
        }
        stage('DockerBuild') {
      steps {
        sh 'docker build -t p2/recApp:latest .'
      }
        }
         stage('DockerRun') {
      steps {
        sh 'docker run -d -p 9090:9090 p2/recApp'
      }
        }
  }
}
